name: Deploy to Azure

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: string
      image_uri:
        description: 'Docker image URI to deploy'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_APP_NAME:
        required: true

jobs:
  deploy:
    name: Deploy to Azure App Service
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Login to Azure
        uses: azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          images: ${{ inputs.image_uri }}
