name: Lint and Format

on:
  workflow_call:
    inputs:
      fail_on_error:
        description: 'Whether to fail the workflow if errors are found'
        required: false
        type: boolean
        default: true

jobs:
  lint:
    name: ESLint & Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: ${{ !inputs.fail_on_error }}

      - name: Check Prettier formatting
        run: npm run format:check
        continue-on-error: ${{ !inputs.fail_on_error }}

      - name: TypeScript type checking
        run: npx tsc --noEmit
        continue-on-error: ${{ !inputs.fail_on_error }}
