name: Security Scan

on:
  workflow_call:
    inputs:
      run_advanced_scans:
        description: 'Whether to run advanced security scans'
        required: false
        type: boolean
        default: false

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=high
        continue-on-error: true

      # Snyk requires a paid account to use API
      #   - name: Run Snyk to check for vulnerabilities
      #     uses: snyk/actions/node@master
      #     continue-on-error: true
      #     env:
      #       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #     with:
      #       args: --severity-threshold=high

      # OWASP Dependency-Check instead of using Snyk
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: '17'
      #     distribution: 'temurin'

      # - name: Verify Java installation
      #   run: |
      #     echo "Java version:"
      #     java -version
      #     echo "JAVA_HOME: $JAVA_HOME"

      # - name: Download OWASP Dependency-Check
      #   run: |
      #     mkdir -p ~/.dependency-check/
      #     wget -q https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
      #     unzip -q dependency-check-12.1.0-release.zip -d ~/.dependency-check/

      # - name: Run OWASP Dependency-Check CLI
      #   run: |
      #     ~/.dependency-check/dependency-check/bin/dependency-check.sh \
      #       --scan . \
      #       --project "Document Portal" \
      #       --format "HTML" \
      #       --out ./reports \
      #       --enableRetired \
      #       --enableExperimental
      #       --nvdApiKey="${{ secrets.NVD_API_KEY }}"
      #   continue-on-error: true
      #   env:
      #     NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      # - name: Upload dependency check report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dependency-check-report
      #     path: ${{ github.workspace }}/reports

      - name: Run CodeQL Analysis
        if: inputs.run_advanced_scans
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        if: inputs.run_advanced_scans
        uses: github/codeql-action/analyze@v3
